# -*- Mode: makefile -*-
#
# ppc64le specific tweaks

VPATH += $(SRC_PATH)/tests/tcg/ppc64le

ifneq ($(DOCKER_IMAGE)$(CROSS_CC_HAS_POWER8_VECTOR),)
PPC64LE_TESTS=bcdsub
endif
bcdsub: CFLAGS += -mpower8-vector

ifneq ($(DOCKER_IMAGE)$(CROSS_CC_HAS_POWER10),)
POWER10_TESTS=byte_reverse cfuged pla pli_33bits setbc test-prefixed-load-store vcfuged
RUN_POWER10_TESTS=$(patsubst %, run-%, $(POWER10_TESTS))
$(RUN_POWER10_TESTS): QEMU_OPTS+=-cpu POWER10
PPC64LE_TESTS += $(POWER10_TESTS)
endif
test-prefixed-load-store: CFLAGS+=-DLE=1

TESTS += $(PPC64LE_TESTS)
